### PR TITLE
feat: patch repository permissions

### PR DESCRIPTION
**Pull request by olenagerasimova**
Part of #5 
Added endpoint to patch repository permissions and test. Also, added exception handlers for invalid json cases and renamed all the repository permissions test classes.

### CODE REVIEW

**Review by g4s8 — APPROVED** [review]
@olenagerasimova thanks

**Comment by g4s8** [comment]
@olenagerasimova please check merge conflict

**Comment by olenagerasimova** [comment]
@g4s8 resolved

**Comment by olenagerasimova** [comment]
@g4s8 please, approve again, I've fixed conflicts

**Review by g4s8 — APPROVED** [review]

**Pull request merged**
