### PR TITLE
feat: Singn in and obtaining JWT-token

### PR DESCRIPTION
**Pull request by andpopov**
close: #102

### CODE REVIEW

**Comment by andpopov** [comment]
I have added getting of JWT-token from Artipie-rest service and usage it in sing in page.
@olenagerasimova, @dgarus Please review

**Comment by olenagerasimova** [comment]
Also, what is the point of a separate page with repositories list? The repositories are listed on the main page:
image

**Comment by andpopov** [comment]
@olenagerasimova thanks for your notes, I have added changes to code.
Currently I selected following endpoints in web-gui, I seem this way will help us to decouple all views as separate endpoints:
- 'repository/list' 
- 'repository/list/:uname'
In feature I am planning to add some "menu" element of web-gui with all added enpoints so user can simply navigate.

**Review by olenagerasimova — APPROVED** [review]
@andpopov thanks, looks good. Though I do not understand why we need `AuthUser` class. Method `getJwtToken()` can accept two strings - username and password and it does not seem as `AuthUser` will have any other usages as dashboard has a single sign-in place. That's just an opinion, approving the PR.

**Comment by andpopov** [comment]
> @andpopov thanks, looks good. Though I do not understand why we need `AuthUser` class. Method `getJwtToken()` can accept two strings - username and password and it does not seem as `AuthUser` will have any other usages as dashboard has a single sign-in place. That's just an opinion, approving the PR.

Thanks @olenagerasimova,
I agree with you opition, removed AuthUser and changed method signature to getJwtToken(name, password) .

**Review by olenagerasimova — APPROVED** [review]

**Pull request merged**
